name = "launchwing-orchestrator"
main = "src/index.ts"
compatibility_date = "2025-08-10"

[assets]
directory = "public"
binding = "ASSETS"

[vars]
# Non-secret vars (safe to commit)
CF_WORKERS_SUBDOMAIN = "promptpulse"
# Make sandbox deploys default to Cloudflare Pages (Advanced Mode)
DEFAULT_DEPLOY_MODE = "pages"