name = "launchwing-orchestrator"
main = "src/index.ts"
compatibility_date = "2025-08-01"

[vars]
# These are set at deploy time (see workflow), but you can override locally:
GIT_REF = "dev"
GIT_SHA = "local"

[observability]
enabled = true

# For local dev, you can put values in .dev.vars