name: Deploy Orchestrator to Cloudflare Workers

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # keep npm from dying on peer-dep chatter during any npm install this job runs
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install repo deps (no lockfile required)
      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Typecheck
        run: npm run typecheck

      # Lint is non-blocking for now
      - name: Lint (non-blocking)
        run: npm run lint

      # Deploy with wrangler-action; pin Wrangler v4 and let npm use legacy peers
      - name: Deploy (wrangler)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '4.28.1'
          command: deploy

      - name: Health check
        run: |
          URL="https://launchwing-orchestrator.${{ secrets.CF_WORKERS_SUBDOMAIN }}.workers.dev/health"
          echo "Hitting $URL"
          curl -fsS "$URL" | tee /tmp/health.json
          jq -e '.ok == true' /tmp/health.json