name: Deploy Orchestrator

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "wrangler.toml"
      - "package.json"
      - ".github/workflows/deploy-orchestrator.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm i -g wrangler@4

      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler deploy \
            --var GIT_SHA:${{ github.sha }} \
            --var GIT_REF:${{ github.ref_name }}

      - name: Healthcheck
        env:
          ORCHESTRATOR_URL: ${{ secrets.ORCHESTRATOR_URL }}
        run: |
          if [ -z "$ORCHESTRATOR_URL" ]; then
            echo "ORCHESTRATOR_URL secret not set; skipping healthcheck"; exit 0
          fi
          curl -fsS "$ORCHESTRATOR_URL/health" | jq .