# .github/workflows/deploy-pages.yml
name: Deploy SPA to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"
      CF_PAGES_PROJECT: "launchwing-app"  # pick once and keep
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps (workspaces ok)
        run: npm install --no-audit --no-fund -ws

      - name: Build SPA → app/dist
        run: npm run -w app build

      # Use Wrangler to deploy Pages (creates project if missing)
      - name: Publish to Pages (wrangler)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # v4 works too; pinning is fine if you prefer
          wranglerVersion: "4"
          command: pages deploy app/dist --project-name ${{ env.CF_PAGES_PROJECT }} --branch main