name: Deploy Orchestrator to Cloudflare Workers

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build SPA → public/
        run: npm run build

      - name: Typecheck
        run: npm run typecheck

      - name: Lint (non-blocking)
        run: npm run lint || true

      # ---------- Inject Worker secrets (token, account, optional email/key, orchestrator URL) ----------
      - name: Set Worker Secrets
        env:
          CLOUDFLARE_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_EMAIL:              ${{ secrets.CLOUDFLARE_EMAIL }}
          CF_KEY:                ${{ secrets.CLOUDFLARE_API_KEY }}
          ORCHESTRATOR_URL:      ${{ secrets.ORCHESTRATOR_URL }}
        run: |
          npx --yes wrangler@4.28.1 --version

          # Token
          yes | npx wrangler@4.28.1 secret delete CLOUDFLARE_API_TOKEN  --name launchwing-orchestrator || true
          printf "%s" "$CLOUDFLARE_API_TOKEN"  | npx wrangler@4.28.1 secret put CLOUDFLARE_API_TOKEN  --name launchwing-orchestrator

          # Account ID
          yes | npx wrangler@4.28.1 secret delete CLOUDFLARE_ACCOUNT_ID --name launchwing-orchestrator || true
          printf "%s" "$CLOUDFLARE_ACCOUNT_ID" | npx wrangler@4.28.1 secret put CLOUDFLARE_ACCOUNT_ID --name launchwing-orchestrator

          # Orchestrator URL (used by generated Pages worker proxy)
          yes | npx wrangler@4.28.1 secret delete ORCHESTRATOR_URL --name launchwing-orchestrator || true
          printf "%s" "$ORCHESTRATOR_URL" | npx wrangler@4.28.1 secret put ORCHESTRATOR_URL --name launchwing-orchestrator

          # Optional legacy auth
          if [ -n "${CF_EMAIL}" ] && [ -n "${CF_KEY}" ]; then
            yes | npx wrangler@4.28.1 secret delete CLOUDFLARE_EMAIL   --name launchwing-orchestrator || true
            yes | npx wrangler@4.28.1 secret delete CLOUDFLARE_API_KEY --name launchwing-orchestrator || true
            printf "%s" "$CF_EMAIL" | npx wrangler@4.28.1 secret put CLOUDFLARE_EMAIL   --name launchwing-orchestrator
            printf "%s" "$CF_KEY"   | npx wrangler@4.28.1 secret put CLOUDFLARE_API_KEY --name launchwing-orchestrator
          fi

      # ------------------------------- Deploy ---------------------------------
      - name: Deploy (wrangler)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.28.1"
          command: deploy

      # --------------------------- Post-deploy checks ---------------------------
      - name: Health check
        env:
          CF_WORKERS_SUBDOMAIN: ${{ vars.CF_WORKERS_SUBDOMAIN }}
        run: |
          SUBDOMAIN="${CF_WORKERS_SUBDOMAIN:-promptpulse}"
          URL="https://launchwing-orchestrator.${SUBDOMAIN}.workers.dev/health"
          echo "Hitting $URL"
          curl -fsS "$URL" | tee /tmp/health.json
          jq -e '.ok == true' /tmp/health.json

      # ✅ Sandbox smoke (ephemeral so it auto-deletes)
      - name: Sandbox deploy smoke (Pages mode, ephemeral)
        env:
          CF_WORKERS_SUBDOMAIN: ${{ vars.CF_WORKERS_SUBDOMAIN }}
        run: |
          SUBDOMAIN="${CF_WORKERS_SUBDOMAIN:-promptpulse}"
          ORCH="https://launchwing-orchestrator.${SUBDOMAIN}.workers.dev"
          echo "POST $ORCH/sandbox-deploy (mode=pages, ephemeral)"
          RESP="$(curl -sS -X POST "$ORCH/sandbox-deploy" \
            -H "content-type: application/json" \
            --data '{"confirm":true,"mode":"pages","ephemeral":true,"name":"lw-sbx-ci"}')"
          echo "$RESP" | tee /tmp/sbx.json
          # Fail only after printing the body
          jq -e '.ok == true and (.url|length>0)' /tmp/sbx.json