name: Deploy SPA to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"
      CF_PAGES_PROJECT: "launchwing-app"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps (workspaces ok)
        run: npm install --no-audit --no-fund -ws

      - name: Build SPA → app/dist
        run: npm run -w app build

      # Idempotent: won't fail if the project already exists
      - name: Create Pages project if missing
        continue-on-error: true
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: >
            pages project create ${{ env.CF_PAGES_PROJECT }}
            --production-branch main
            --compatibility-date 2024-11-01

      # Deploy static build + Pages Functions under app/functions
      - name: Publish to Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: >
            --cwd app
            pages deploy dist
            --project-name ${{ env.CF_PAGES_PROJECT }}
            --branch main
            --commit-dirty=true