name: Deploy Orchestrator (Cloudflare Worker)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install (workspaces ok)
        run: npm install --no-audit --no-fund -ws

      - name: Build orchestrator (ok if no-op)
        run: npm run -w . build || true

      - name: Deploy Worker with commit variables
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: >
            deploy
            --var GIT_SHA:${{ github.sha }}
            --var GIT_REF:${{ github.ref_name }}

      - name: Verify /health git_sha matches this commit
        run: |
          set -euo pipefail
          echo "Expect SHA: $GITHUB_SHA"
          body="$(curl -fsS https://launchwing-orchestrator.promptpulse.workers.dev/health)"
          echo "$body" | jq .
          got="$(echo "$body" | jq -r '.git_sha')"
          if [ -z "$got" ] || [ "$got" != "$GITHUB_SHA" ]; then
            echo "❌ git_sha mismatch: got=$got expected=$GITHUB_SHA"
            exit 1
          fi
          echo "✅ Worker /health.git_sha matches"